---
title: Josh Waller
description: A Father, Husband, Frontend Engineer, Musician, and Comic Book Junkie
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  music:
    title: Music
    output: false
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
permalink: "/blog/:slug"
profile_img: "https://avatars3.githubusercontent.com/u/1900735?s=460&v=4"
baseurl: "/"
url: https://joshwaller.me
author: Josh Waller
twitter:
  username: mdxprograms
  card: summary
paginate: 5
github:
  url: https://github.com/mdxprograms
  repo: https://github.com/mdxprograms/joshwaller.me
plugins:
  - jekyll-seo-tag
exclude:
  - "node_modules"
  - ".git"
  - "_lib"
  - "package.json"
  - "package-lock.json"
  - "Gemfile"
  - "Rakefile"
  - "README.md"
