---
title: Josh Waller
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
permalink: "/blog/:slug"
profile_img: "https://avatars3.githubusercontent.com/u/1900735?s=460&v=4"
baseurl: "/"
url: https://mdxprograms.github.io
author:
  name: Josh Waller
  url: https://twitter.com/mdxprograms
paginate: 5
github:
  url: https://github.com/mdxprograms
  repo: https://github.com/mdxprograms/mdxprograms.github.io
