# Permalinks
permalink: /:categories/:title

# Setup
baseurl: "/"
title: "Josh Waller"
url: "https://mdxprograms.github.io"

author:
  name: 'Josh Waller'
  url: "https://twitter.com/mdxprograms"

paginate: 5

github:
  url: "https://github.com/mdxprograms"
  repo: "https://github.com/mdxprograms/mdxprograms.github.io"

# build
incremental: true

collections:
  resources:
    output: true
    permalink: /resources/:path
