---
title:                      Josh Waller
highlighter:                none
markdown:                   kramdown
kramdown:
   syntax_highlighter_opts:
      disable :             true
timezone:                   America/New_York
collections:
  projects:
    title:                  Projects
    output:                 true
    layout:                 page
  resources:
    title:                  Resources
    output:                 true
    permalink:              "/resources/:path"
  uploads:
    title:                  Uploads
    output:                 true
permalink:                  /blog/:slug
baseurl:                    "/"
url:                        https://mdxprograms.github.io
author:
  name:                     Josh Waller
  url:                      https://twitter.com/mdxprograms
paginate:                   5
github:
  url:                      https://github.com/mdxprograms
  repo:                     https://github.com/mdxprograms/mdxprograms.github.io
