---
title: Josh Waller
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
    permalink: "/resources/:path"
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title"
baseurl: "/"
url: https://mdxprograms.github.io
author:
  name: Josh Waller
  url: https://twitter.com/mdxprograms
paginate: 5
github:
  url: https://github.com/mdxprograms
  repo: https://github.com/mdxprograms/mdxprograms.github.io
incremental: true
